# Assignment 04

## 1.1

Super simple MDP with 10 states. Agent move in a straight line. Deciedes if he wants
to move or stay at the same place. If he stays it's a 0 cost and if he moves it costs him 1 (-1 reward). Arriving half way he gets 10 reward and if he
manages to go to the end state he will receive a huge reward.

Probability that the agent gets to the next state if he decides to move is 0.7
And with 0.3 probability he will go back to starting position.

## 1.2 Implementation

DiscreteMDP, ValueIteration, Policy Iteration code were taken from the rldmuu github.

In [62]:
from MDP import DiscreteMDP


class MySuperSimpleMDP(DiscreteMDP):
  def __init__(self, n_states):
    
    super().__init__(n_states=n_states, n_actions=2)
    
    self.STAY = 0
    self.MOVE = 1
    
    self.P[:] = 0
    self.R[:] = 0
    self.R[:, self.MOVE] = -1
    self.R[:, self.STAY] = 0
    
    self.R[n_states - 1,:] = 100
    self.R[n_states // 2 - 1,:] = 10
    
    for s in range(n_states):
      self.P[s, self.STAY, s] = 1
      
      if s == n_states - 1:
        self.P[s, self.MOVE, s] = 1
      else:
        self.P[s, self.MOVE, s + 1] = 0.7
        self.P[s, self.MOVE, 0] = 0.3

## 1.3

In [63]:
mdp = MySuperSimpleMDP(10)

In [64]:
from ValueIteration import value_iteration
import numpy as np

for gamma in np.arange(0.1, 1, 0.1):
  policy, V, Q = value_iteration(mdp, 1000, gamma)
  print(f"gamma: {gamma} policy:")
  print(policy)
  print("Value function")
  print(V)



gamma: 0.1 policy:
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Value function
[  0.           0.           0.           0.          11.11111111
   0.           0.           0.           6.77777778 111.11111111]
gamma: 0.2 policy:
[0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
Value function
[  0.     0.     0.     0.75  12.5    0.     0.     1.31  16.5  125.  ]
gamma: 0.30000000000000004 policy:
[0. 0. 0. 1. 0. 0. 1. 1. 1. 0.]
Value function
[0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e+00
 1.42857143e+01 0.00000000e+00 6.89000000e-02 5.09000000e+00
 2.90000000e+01 1.42857143e+02]
gamma: 0.4 policy:
[0. 0. 1. 1. 0. 0. 1. 1. 1. 0.]
Value function
[0.00000000e+00 0.00000000e+00 2.66666667e-02 3.66666667e+00
 1.66666667e+01 0.00000000e+00 2.30026667e+00 1.17866667e+01
 4.56666667e+01 1.66666667e+02]
gamma: 0.5 policy:
[0. 0. 1. 1. 0. 1. 1. 1. 1. 0.]
Value function
[  0.         0.         1.1        6.        20.         1.485875
   7.1025    23.15      69.       200.      ]
gamma: 0.6000000000000001 po

In [58]:
from PolicyIteration import policy_iteration

for gamma in np.arange(0.1, 1, 0.1):
  policy, V, Q = policy_iteration(mdp, 10000, gamma, 100)
  print(f"gamma: {gamma} policy:")
  print(policy)

gamma: 0.1 policy:
[0 0 0 1 0 0 0 1 1 0]
gamma: 0.2 policy:
[0 0 0 1 0 0 1 1 1 0]
gamma: 0.30000000000000004 policy:
[0 0 1 1 0 1 1 1 1 0]
gamma: 0.4 policy:
[0 0 1 1 0 1 1 1 1 0]
gamma: 0.5 policy:
[0 1 1 1 0 1 1 1 1 0]
gamma: 0.6000000000000001 policy:
[1 1 1 1 1 1 1 1 1 0]
gamma: 0.7000000000000001 policy:
[1 1 1 1 1 1 1 1 1 0]
gamma: 0.8 policy:
[1 1 1 1 1 1 1 1 1 0]
gamma: 0.9 policy:
[1 1 1 1 1 1 1 1 1 0]


### Discussion

With this super simple MDP example, we clearly see that the policy depends on gamma.\
In the value iteration algorithm.\
Same conclusions with the policy iteration algorithm

In this example it's obvious that more future rewards are important\
more you want to move in the direction of the end state.

The value of a state is the potential value that a given state can achieve\
if we follow the optimal policy from this state onward.


I was planning on extending or doing a more complicated example but maybe for\
next time. This helped me in understanding the material.


## 3 Feedback

1. Most interesting and useful material so far to me. New MDP Book 2026 from Putterman super useful to get a stronger grasp\
of the course material.
2. 
3. Value Iteration and MDP principles
4. Policy Iteration
5. MDP modelling/design
6. See practical examples. Build and think about my own MDP (even if super simple)
7.  
8. Yes
9. Yes
10. 